flowchart TD
    A[FBS <br> target_name<br> observation_reason <br> science_program <br>scheduler_note]
    -->|Scheduler|C[JSON BLOCK <br> $name <br> $reason <br> $program <br> $note]
    B[Add BLOCK <br> $name <br> $reason <br> $program <br> $note]
    -->|Scheduler|C
    C -->|ScriptQueue|D[nextVisit<br>survey<br>groupId]
    C ---->|ScriptQueue|E[Ptg.currentTarget.targetName<br>name]
    C ---->|ScriptQueue|F[Camera.startIntegration.additionalKeys<br>reason, program, imageType, groupId]
    C ---->|ScriptQueue|G[Camera.imageReadoutParameters.daqAnnotation<br>note]
    E -->|HeaderService|H[FITS Headers<br>OBJECT<br>REASON<br>PROGRAM<br>OBSANNOT<br>IMGTYPE<br>GROUPID]
    F -->|HeaderService|H
    G -->|HeaderService|H
    H -->|MetadataTranslator|I[ObservationInfo<br>science_program<br>observation_reason<br>target_name<br>observation_type<br>exposure_group]
    I -->J[Butler exposure records<br>science_program<br>observation_reason<br>target_name<br>observation_type<br>group]
    I -->K[ConsDb<br> target_name<br> observation_reason<br>science_program<br>img_type<br>group_id]
